language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.3.1
install: pip install -r requirements.txt --use-mirrors
script:  python scielomanager/manage.py test journalmanager
before_script:
  - psql -c 'create database journalmanager;' -U postgres
postgres:
  adapter: postgresql
  database: journalmanager
  username: postgres
