language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.3.1
install:
  - pip install -r requirements.txt --use-mirrors
after_install:
  - cp settings_local.include-TEMPLATE settings_local.include
before_script:
  - psql -c 'create database journalmanager;' -U postgres
script:
  - python scielomanager/manage.py test journalmanager
postgres:
  adapter: postgresql
  database: journalmanager
  username: postgres
