sudo: false
language: python
python:
  - 2.7
env:
  - DJANGO_VERSION=1.4 SCIELOMANAGER_SETTINGS_FILE=`pwd`/scielomanager/scielomanager/settings_local.include
before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - cp scielomanager/scielomanager/settings_local.include-TEMPLATE scielomanager/scielomanager/settings_local.include
  - psql -c 'create database journalmanager;' -U postgres
script:
  - make test
